name: Deploymen pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Ubuntu-18.04
    steps:
      - name: Import repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test
