name: Deploymen pipeline
on:
  push:
    branches:
      - main
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  cancel_previous_job:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redundant build
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-latest
    steps:     
      - name: Import repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:     
      - name: Import repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run lint
  
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:     
      - name: Import repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional     
      - name: Build
        run: npm run build
      - name: save artifact for other jobs
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:     
      - name: Import repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional 
      - name: download artifact from other jobs
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist 
      - name: Tests
        run: npm test      
